# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/LayneBookstoreTransact/api/categories
Accept: application/json

###

POST http://localhost:8080/LayneBookstoreTransact/api/orders
Accept: */*
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Origin: http://localhost:8081
Referer: http://localhost:8081/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Content-Type: application/json

{
  "cart": {
    "itemArray": [
      {
        "book": {
          "bookId": 1003,
          "title": "Journey to the Center of the Earth",
          "author": "Jules Verne",
          "description": "",
          "price": 499,
          "rating": 0,
          "isPublic": false,
          "isFeatured": false,
          "categoryId": 1001
        },
        "quantity": 1
      }
    ]
  },
  "customerForm": {
    "name": "Layne",
    "address": "taipei",
    "phone": "(571) 265-7610",
    "email": "layen.ln.pu@gmail.com",
    "ccNumber": "4444-3333-2222-1111",
    "ccExpiryMonth": 12,
    "ccExpiryYear": 2022
  }
}

###


